CREATE TABLE IF NOT EXISTS paiement (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    montant DECIMAL(10,2) NOT NULL,
    mode_paiement VARCHAR(50) NOT NULL,
    statut ENUM('EN_ATTENTE','SUCCES','REFUSE')
           NOT NULL DEFAULT 'EN_ATTENTE',
    date_paiement DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
